[profile.default]
solc = "0.8.29"
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache/forge'
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [
	{ access = "read", path = "out" },
	{ access = "read", path = "rpgf2_results.csv" },
]
optimizer = true
optimizer_runs = 200


[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
sepolia = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
localhost = "http://localhost:8545"
sepolia = "https://sepolia.drpc.org"
